# This is a basic workflow to help you get started with Actions

name: first with spaces

on:
  workflow_dispatch:


jobs:
  req:
    runs-on: ubuntu-latest
    steps:
      - name: foo
        run: |
          echo "foo"
