# This is a basic workflow to help you get started with Actions

name: second

# Controls when the workflow will run
on:
  workflow_dispatch:
  workflow_run:
    workflows: 
      - "first+with+spaces"
      - first_no_spaces
    types:
      - completed


jobs:
  req:
    runs-on: ubuntu-latest
    steps:
      - name: bar
        run: |
          echo "bar"
    
